package superlord.wildlands.init;

import net.minecraft.core.Direction;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.SignItem;
import net.minecraft.world.level.material.Fluids;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import superlord.wildlands.WildLands;
import superlord.wildlands.common.entity.WLBoat;
import superlord.wildlands.common.item.CoconutItem;
import superlord.wildlands.common.item.DuckweedItem;
import superlord.wildlands.common.item.JellyItem;
import superlord.wildlands.common.item.WLBoatItem;
import superlord.wildlands.common.item.WLBucketItem;
import superlord.wildlands.common.item.WLChestBoatItem;

public class WLItems {

	public static final DeferredRegister<Item> REGISTER = DeferredRegister.create(ForgeRegistries.ITEMS, WildLands.MOD_ID);
	public static final DeferredRegister<Item> BLOCKS = DeferredRegister.create(ForgeRegistries.ITEMS, WildLands.MOD_ID);
	public static final DeferredRegister<Item> SPAWN_EGGS = DeferredRegister.create(ForgeRegistries.ITEMS, WildLands.MOD_ID);

	public static final RegistryObject<Item> OLIVINE = REGISTER.register("olivine", () -> new Item(new Item.Properties()));
	//public static final RegistryObject<Item> PEARL = REGISTER.register("pearl", () -> new Item(new Item.Properties()));
	public static final RegistryObject<BlockItem> MUD = BLOCKS.register("mud", () -> new BlockItem(WLBlocks.MUD.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_LOG = BLOCKS.register("cypress_log", () -> new BlockItem(WLBlocks.CYPRESS_LOG.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> STRIPPED_CYPRESS_LOG = BLOCKS.register("stripped_cypress_log", () -> new BlockItem(WLBlocks.STRIPPED_CYPRESS_LOG.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_LOG = BLOCKS.register("coconut_log", () -> new BlockItem(WLBlocks.COCONUT_LOG.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> STRIPPED_COCONUT_LOG = BLOCKS.register("stripped_coconut_log", () -> new BlockItem(WLBlocks.STRIPPED_COCONUT_LOG.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_LOG = BLOCKS.register("charred_log", () -> new BlockItem(WLBlocks.CHARRED_LOG.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> STRIPPED_CHARRED_LOG = BLOCKS.register("stripped_charred_log", () -> new BlockItem(WLBlocks.STRIPPED_CHARRED_LOG.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_WOOD = BLOCKS.register("cypress_wood", () -> new BlockItem(WLBlocks.CYPRESS_WOOD.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> STRIPPED_CYPRESS_WOOD = BLOCKS.register("stripped_cypress_wood", () -> new BlockItem(WLBlocks.STRIPPED_CYPRESS_WOOD.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_WOOD = BLOCKS.register("coconut_wood", () -> new BlockItem(WLBlocks.COCONUT_WOOD.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> STRIPPED_COCONUT_WOOD = BLOCKS.register("stripped_coconut_wood", () -> new BlockItem(WLBlocks.STRIPPED_COCONUT_WOOD.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_WOOD = BLOCKS.register("charred_wood", () -> new BlockItem(WLBlocks.CHARRED_WOOD.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> STRIPPED_CHARRED_WOOD = BLOCKS.register("stripped_charred_wood", () -> new BlockItem(WLBlocks.STRIPPED_CHARRED_WOOD.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> SMOLDERING_LOG = BLOCKS.register("smoldering_log", () -> new BlockItem(WLBlocks.SMOLDERING_LOG.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_PLANKS = BLOCKS.register("cypress_planks", () -> new BlockItem(WLBlocks.CYPRESS_PLANKS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_PLANKS = BLOCKS.register("coconut_planks", () -> new BlockItem(WLBlocks.COCONUT_PLANKS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_PLANKS = BLOCKS.register("charred_planks", () -> new BlockItem(WLBlocks.CHARRED_PLANKS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_DOOR = BLOCKS.register("cypress_door", () -> new BlockItem(WLBlocks.CYPRESS_DOOR.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_DOOR = BLOCKS.register("coconut_door", () -> new BlockItem(WLBlocks.COCONUT_DOOR.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_DOOR = BLOCKS.register("charred_door", () -> new BlockItem(WLBlocks.CHARRED_DOOR.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_LEAVES = BLOCKS.register("cypress_leaves", () -> new BlockItem(WLBlocks.CYPRESS_LEAVES.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_LEAVES = BLOCKS.register("coconut_leaves", () -> new BlockItem(WLBlocks.COCONUT_LEAVES.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_STAIRS = BLOCKS.register("cypress_stairs", () -> new BlockItem(WLBlocks.CYPRESS_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_STAIRS = BLOCKS.register("coconut_stairs", () -> new BlockItem(WLBlocks.COCONUT_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_STAIRS = BLOCKS.register("charred_stairs", () -> new BlockItem(WLBlocks.CHARRED_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_PRESSURE_PLATE = BLOCKS.register("cypress_pressure_plate", () -> new BlockItem(WLBlocks.CYPRESS_PRESSURE_PLATE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_PRESSURE_PLATE = BLOCKS.register("coconut_pressure_plate", () -> new BlockItem(WLBlocks.COCONUT_PRESSURE_PLATE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_PRESSURE_PLATE = BLOCKS.register("charred_pressure_plate", () -> new BlockItem(WLBlocks.CHARRED_PRESSURE_PLATE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_BUTTON = BLOCKS.register("cypress_button", () -> new BlockItem(WLBlocks.CYPRESS_BUTTON.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_BUTTON = BLOCKS.register("coconut_button", () -> new BlockItem(WLBlocks.COCONUT_BUTTON.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_BUTTON = BLOCKS.register("charred_button", () -> new BlockItem(WLBlocks.CHARRED_BUTTON.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_FENCE = BLOCKS.register("cypress_fence", () -> new BlockItem(WLBlocks.CYPRESS_FENCE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_FENCE = BLOCKS.register("coconut_fence", () -> new BlockItem(WLBlocks.COCONUT_FENCE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_FENCE = BLOCKS.register("charred_fence", () -> new BlockItem(WLBlocks.CHARRED_FENCE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_TRAPDOOR = BLOCKS.register("cypress_trapdoor", () -> new BlockItem(WLBlocks.CYPRESS_TRAPDOOR.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_TRAPDOOR = BLOCKS.register("coconut_trapdoor", () -> new BlockItem(WLBlocks.COCONUT_TRAPDOOR.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_TRAPDOOR = BLOCKS.register("charred_trapdoor", () -> new BlockItem(WLBlocks.CHARRED_TRAPDOOR.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_FENCE_GATE = BLOCKS.register("cypress_fence_gate", () -> new BlockItem(WLBlocks.CYPRESS_FENCE_GATE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_FENCE_GATE = BLOCKS.register("coconut_fence_gate", () -> new BlockItem(WLBlocks.COCONUT_FENCE_GATE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_FENCE_GATE = BLOCKS.register("charred_fence_gate", () -> new BlockItem(WLBlocks.CHARRED_FENCE_GATE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_SLAB = BLOCKS.register("cypress_slab", () -> new BlockItem(WLBlocks.CYPRESS_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_SLAB = BLOCKS.register("coconut_slab", () -> new BlockItem(WLBlocks.COCONUT_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_SLAB = BLOCKS.register("charred_slab", () -> new BlockItem(WLBlocks.CHARRED_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CYPRESS_SAPLING = BLOCKS.register("cypress_sapling", () -> new BlockItem(WLBlocks.CYPRESS_SAPLING.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> COCONUT_SAPLING = BLOCKS.register("coconut_sapling", () -> new BlockItem(WLBlocks.COCONUT_SAPLING.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> PALMETTO = BLOCKS.register("palmetto", () -> new BlockItem(WLBlocks.PALMETTO.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CATTAIL = BLOCKS.register("cattail", () -> new BlockItem(WLBlocks.CATTAIL.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> DUCKWEED = BLOCKS.register("duckweed", () -> new DuckweedItem(WLBlocks.DUCKWEED.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> BEARD_MOSS = BLOCKS.register("beard_moss", () -> new BlockItem(WLBlocks.BEARD_MOSS_TOP.get(), new Item.Properties()));
	public static final RegistryObject<Item> RAW_CATFISH = REGISTER.register("raw_catfish", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(3).saturationMod(0.1F).meat().build())));
	public static final RegistryObject<Item> ANCHOVY = REGISTER.register("anchovy", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).fast().meat().build())));
	public static final RegistryObject<Item> CRAB_CLAW = REGISTER.register("crab_claw", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(2).saturationMod(0.1F).meat().build())));
	public static final RegistryObject<Item> COOKED_CATFISH = REGISTER.register("cooked_catfish", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(8).saturationMod(0.8F).meat().build())));
	public static final RegistryObject<Item> COOKED_ANCHOVY = REGISTER.register("cooked_anchovy", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(5).saturationMod(0.6F).fast().meat().build())));
	public static final RegistryObject<Item> COOKED_CRAB_CLAW = REGISTER.register("cooked_crab_claw", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().nutrition(6).saturationMod(0.6F).meat().build())));
	public static final RegistryObject<WLBucketItem> CATFISH_BUCKET = REGISTER.register("catfish_bucket", () -> new WLBucketItem(WLEntities.CATFISH, () -> Fluids.WATER, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<WLBucketItem> ALLIGATOR_BUCKET = REGISTER.register("alligator_bucket", () -> new WLBucketItem(WLEntities.ALLIGATOR, () -> Fluids.WATER, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<WLBucketItem> ANCHOVY_BUCKET = REGISTER.register("anchovy_bucket", () -> new WLBucketItem(WLEntities.ANCHOVY, () -> Fluids.WATER, new Item.Properties().stacksTo(1)));
	public static final RegistryObject<Item> CATFISH_SPAWN_EGG = SPAWN_EGGS.register("catfish_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.CATFISH, 0xC9A764, 0x7E774F, new Item.Properties()));
	public static final RegistryObject<Item> ALLIGATOR_SPAWN_EGG = SPAWN_EGGS.register("alligator_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.ALLIGATOR, 0x5A6C43, 0x89915A, new Item.Properties()));
	public static final RegistryObject<Item> CRAB_SPAWN_EGG = SPAWN_EGGS.register("crab_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.CRAB, 0x872B2F, 0xE74D3C, new Item.Properties()));
	public static final RegistryObject<Item> SEA_LION_SPAWN_EGG = SPAWN_EGGS.register("sea_lion_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.SEA_LION, 0x865726, 0x251711, new Item.Properties()));
	public static final RegistryObject<BlockItem> CONGLOMERATE = BLOCKS.register("conglomerate", () -> new BlockItem(WLBlocks.CONGLOMERATE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CONGLOMERATE_SLAB = BLOCKS.register("conglomerate_slab", () -> new BlockItem(WLBlocks.CONGLOMERATE_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CONGLOMERATE_STAIRS = BLOCKS.register("conglomerate_stairs", () -> new BlockItem(WLBlocks.CONGLOMERATE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CONGLOMERATE_BRICKS = BLOCKS.register("conglomerate_bricks", () -> new BlockItem(WLBlocks.CONGLOMERATE_BRICKS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CONGLOMERATE_BRICK_SLAB = BLOCKS.register("conglomerate_brick_slab", () -> new BlockItem(WLBlocks.CONGLOMERATE_BRICK_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CONGLOMERATE_BRICK_STAIRS = BLOCKS.register("conglomerate_brick_stairs", () -> new BlockItem(WLBlocks.CONGLOMERATE_BRICK_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CONGLOMERATE_BRICK_WALL = BLOCKS.register("conglomerate_brick_wall", () -> new BlockItem(WLBlocks.CONGLOMERATE_BRICK_WALL.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> GABBRO = BLOCKS.register("gabbro", () -> new BlockItem(WLBlocks.GABBRO.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> OLIVINE_GABBRO = BLOCKS.register("olivine_gabbro", () -> new BlockItem(WLBlocks.OLIVINE_GABBRO.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> GABBRO_SLAB = BLOCKS.register("gabbro_slab", () -> new BlockItem(WLBlocks.GABBRO_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> GABBRO_STAIRS = BLOCKS.register("gabbro_stairs", () -> new BlockItem(WLBlocks.GABBRO_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> GABBRO_WALL = BLOCKS.register("gabbro_wall", () -> new BlockItem(WLBlocks.GABBRO_WALL.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> POLISHED_GABBRO = BLOCKS.register("polished_gabbro", () -> new BlockItem(WLBlocks.POLISHED_GABBRO.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> POLISHED_GABBRO_SLAB = BLOCKS.register("polished_gabbro_slab", () -> new BlockItem(WLBlocks.POLISHED_GABBRO_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> POLISHED_GABBRO_STAIRS = BLOCKS.register("polished_gabbro_stairs", () -> new BlockItem(WLBlocks.POLISHED_GABBRO_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> DOLERITE = BLOCKS.register("dolerite", () -> new BlockItem(WLBlocks.DOLERITE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> DOLERITE_SLAB = BLOCKS.register("dolerite_slab", () -> new BlockItem(WLBlocks.DOLERITE_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> DOLERITE_STAIRS = BLOCKS.register("dolerite_stairs", () -> new BlockItem(WLBlocks.DOLERITE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> DOLERITE_WALL = BLOCKS.register("dolerite_wall", () -> new BlockItem(WLBlocks.DOLERITE_WALL.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> POLISHED_DOLERITE = BLOCKS.register("polished_dolerite", () -> new BlockItem(WLBlocks.POLISHED_DOLERITE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> POLISHED_DOLERITE_SLAB = BLOCKS.register("polished_dolerite_slab", () -> new BlockItem(WLBlocks.POLISHED_DOLERITE_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> POLISHED_DOLERITE_STAIRS = BLOCKS.register("polished_dolerite_stairs", () -> new BlockItem(WLBlocks.POLISHED_DOLERITE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> FINE_SAND = BLOCKS.register("fine_sand", () -> new BlockItem(WLBlocks.FINE_SAND.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> FINE_SANDSTONE = BLOCKS.register("fine_sandstone", () -> new BlockItem(WLBlocks.FINE_SANDSTONE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> FINE_SANDSTONE_SLAB = BLOCKS.register("fine_sandstone_slab", () -> new BlockItem(WLBlocks.FINE_SANDSTONE_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> FINE_SANDSTONE_STAIRS = BLOCKS.register("fine_sandstone_stairs", () -> new BlockItem(WLBlocks.FINE_SANDSTONE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> FINE_SANDSTONE_WALL = BLOCKS.register("fine_sandstone_wall", () -> new BlockItem(WLBlocks.FINE_SANDSTONE_WALL.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> SMOOTH_FINE_SANDSTONE = BLOCKS.register("smooth_fine_sandstone", () -> new BlockItem(WLBlocks.SMOOTH_FINE_SANDSTONE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> SMOOTH_FINE_SANDSTONE_SLAB = BLOCKS.register("smooth_fine_sandstone_slab", () -> new BlockItem(WLBlocks.SMOOTH_FINE_SANDSTONE_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> SMOOTH_FINE_SANDSTONE_STAIRS = BLOCKS.register("smooth_fine_sandstone_stairs", () -> new BlockItem(WLBlocks.SMOOTH_FINE_SANDSTONE_STAIRS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CUT_FINE_SANDSTONE = BLOCKS.register("cut_fine_sandstone", () -> new BlockItem(WLBlocks.CUT_FINE_SANDSTONE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CUT_FINE_SANDSTONE_SLAB = BLOCKS.register("cut_fine_sandstone_slab", () -> new BlockItem(WLBlocks.CUT_FINE_SANDSTONE_SLAB.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> OLIVINE_BLOCK = BLOCKS.register("olivine_block", () -> new BlockItem(WLBlocks.OLIVINE.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> OLIVINE_LAMP = BLOCKS.register("olivine_lamp", () -> new BlockItem(WLBlocks.OLIVINE_LAMP.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> OLIVINE_PRESSURE_PLATE = BLOCKS.register("olivine_pressure_plate", () -> new BlockItem(WLBlocks.OLIVINE_PRESSURE_PLATE.get(), new Item.Properties()));
	//public static final RegistryObject<BlockItem> PEARL_BLOCK = REGISTER.register("pearl_block", () -> new BlockItem(WLBlocks.PEARL.get(), new Item.Properties()));
	//public static final RegistryObject<BlockItem> PEARL_TILE_BLOCK = REGISTER.register("pearl_tile_block", () -> new BlockItem(WLBlocks.PEARL_TILES.get(), new Item.Properties()));
	public static final RegistryObject<CoconutItem> COCONUT = BLOCKS.register("coconut", () -> new CoconutItem(WLBlocks.COCONUT.get(), WLBlocks.WALL_COCONUT.get(), new Item.Properties().stacksTo(16), Direction.DOWN));
	public static final RegistryObject<Item> CRACKED_COCONUT = REGISTER.register("cracked_coconut", () -> new Item(new Item.Properties().food(new FoodProperties.Builder().saturationMod(0.3F).nutrition(2).build())));
	public static final RegistryObject<JellyItem> JELLY_BALL = REGISTER.register("jelly_ball", () -> new JellyItem(new Item.Properties()));
	public static final RegistryObject<BlockItem> JELLY_BLOCK = BLOCKS.register("jelly_block", () -> new BlockItem(WLBlocks.JELLY_BLOCK.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> BLUE_STARFISH = BLOCKS.register("blue_starfish", () -> new BlockItem(WLBlocks.BLUE_STARFISH.get(), new Item.Properties().stacksTo(1)));
	public static final RegistryObject<BlockItem> MAGENTA_STARFISH = BLOCKS.register("magenta_starfish", () -> new BlockItem(WLBlocks.MAGENTA_STARFISH.get(), new Item.Properties().stacksTo(1)));
	public static final RegistryObject<BlockItem> ORANGE_STARFISH = BLOCKS.register("orange_starfish", () -> new BlockItem(WLBlocks.ORANGE_STARFISH.get(), new Item.Properties().stacksTo(1)));
	public static final RegistryObject<BlockItem> PINK_STARFISH = BLOCKS.register("pink_starfish", () -> new BlockItem(WLBlocks.PINK_STARFISH.get(), new Item.Properties().stacksTo(1)));
	public static final RegistryObject<BlockItem> RED_STARFISH = BLOCKS.register("red_starfish", () -> new BlockItem(WLBlocks.RED_STARFISH.get(), new Item.Properties().stacksTo(1)));
	public static final RegistryObject<BlockItem> URCHIN = BLOCKS.register("urchin", () -> new BlockItem(WLBlocks.URCHIN.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> SEAWEED_BLOCK = BLOCKS.register("seaweed_block", () -> new BlockItem(WLBlocks.SEAWEED_BLOCK.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_GRASS = BLOCKS.register("charred_grass", () -> new BlockItem(WLBlocks.CHARRED_GRASS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_TALL_GRASS = BLOCKS.register("charred_tall_grass", () -> new BlockItem(WLBlocks.CHARRED_TALL_GRASS.get(), new Item.Properties()));
	public static final RegistryObject<BlockItem> CHARRED_BUSH = BLOCKS.register("charred_bush", () -> new BlockItem(WLBlocks.CHARRED_BUSH.get(), new Item.Properties()));
	
	public static final RegistryObject<WLBoatItem> CYPRESS_BOAT = REGISTER.register("bald_cypress_boat", () -> new WLBoatItem(WLBoat.WLBoatTypes.CYPRESS, (new Item.Properties().stacksTo(1))));
	public static final RegistryObject<WLBoatItem> COCONUT_BOAT = REGISTER.register("coconut_boat", () -> new WLBoatItem(WLBoat.WLBoatTypes.COCONUT, (new Item.Properties().stacksTo(1))));
	public static final RegistryObject<WLBoatItem> CHARRED_BOAT = REGISTER.register("charred_boat", () -> new WLBoatItem(WLBoat.WLBoatTypes.CHARRED, (new Item.Properties().stacksTo(1))));
	public static final RegistryObject<WLChestBoatItem> CYPRESS_CHEST_BOAT = REGISTER.register("bald_cypress_chest_boat", () -> new WLChestBoatItem(WLBoat.WLBoatTypes.CYPRESS, (new Item.Properties().stacksTo(1))));
	public static final RegistryObject<WLChestBoatItem> COCONUT_CHEST_BOAT = REGISTER.register("coconut_chest_boat", () -> new WLChestBoatItem(WLBoat.WLBoatTypes.COCONUT, (new Item.Properties().stacksTo(1))));
	public static final RegistryObject<WLChestBoatItem> CHARRED_CHEST_BOAT = REGISTER.register("charred_chest_boat", () -> new WLChestBoatItem(WLBoat.WLBoatTypes.CHARRED, (new Item.Properties().stacksTo(1))));

	//public static final RegistryObject<Item> CLAM_SPAWN_EGG = REGISTER.register("clam_spawn_egg", () -> new WLSpawnEggItem(WLEntities.CLAM, 0x674F57, 0xE2C19D, new Item.Properties()));
	public static final RegistryObject<Item> HAMMERHEAD_SPAWN_EGG = SPAWN_EGGS.register("hammerhead_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.HAMMERHEAD, 0x6F594C, 0xDBCCBC, new Item.Properties()));
	public static final RegistryObject<Item> ANCHOVY_SPAWN_EGG = SPAWN_EGGS.register("anchovy_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.ANCHOVY, 0xD6D6D6, 0x454B5D, new Item.Properties()));
	public static final RegistryObject<Item> OCTOPUS_SPAWN_EGG = SPAWN_EGGS.register("octopus_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.OCTOPUS, 0x6E2354, 0xEC4DA7, new Item.Properties())); 
	public static final RegistryObject<Item> JELLYFISH_SPAWN_EGG = SPAWN_EGGS.register("jellyfish_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.JELLYFISH, 0xFB87A7, 0xE06595, new Item.Properties()));
	public static final RegistryObject<Item> GRIZZLY_BEAR_SPAWN_EGG = SPAWN_EGGS.register("grizzly_bear_spawn_egg", () -> new ForgeSpawnEggItem(WLEntities.GRIZZLY, 0x491F10, 0x8C572B, new Item.Properties()));
	public static final RegistryObject<Item> CYPRESS_SIGN = BLOCKS.register("cypress_sign", () -> new SignItem(new Item.Properties().stacksTo(16), WLBlocks.CYPRESS_SIGN.get(), WLBlocks.CYPRESS_WALL_SIGN.get()));
	public static final RegistryObject<Item> COCONUT_SIGN = BLOCKS.register("coconut_sign", () -> new SignItem(new Item.Properties().stacksTo(16), WLBlocks.COCONUT_SIGN.get(), WLBlocks.COCONUT_WALL_SIGN.get()));
	public static final RegistryObject<Item> CHARRED_SIGN = BLOCKS.register("charred_sign", () -> new SignItem(new Item.Properties().stacksTo(16), WLBlocks.CHARRED_SIGN.get(), WLBlocks.CHARRED_WALL_SIGN.get()));
}
